services:
    laravel.test:
        build:
            context: ./
            dockerfile: Dockerfile
        image: php:8.3-fpm
        working_dir: /var/www
        volumes:
            - './:/var/www'
        networks:
            - laravel.test_network
        depends_on:
            - mysql
            - mailpit
            - redis
    mysql:
        image: 'mysql:8.0'
        ports:
            - "3337:3306"
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: laravel.test_db
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - laravel.test_network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - laravel.test_network
    redis:
        image: 'redis:alpine'
        ports:
            - "6379:6379"
        volumes:
            - 'redis:/data'
        networks:
            - laravel.test_network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    NGINX:
        image: nginx:alpine
        volumes:
            - ./docker-compose/nginx/:/etc/nginx/conf.d
            - ./:/var/www
        ports:
            - "8080:80"
        networks:
            - laravel.test_network
        depends_on:
            - laravel.test
networks:
    laravel.test_network:
        driver: bridge
volumes:
    mysql:
        driver: local
    redis:
        driver: local
